// Generated by CoffeeScript 1.6.2
(function() {
  var gmapinit;

  gmapinit = function() {
    var map, mapOptions;

    mapOptions = {
      zoom: 8,
      center: new google.maps.LatLng(-34.397, 150.644),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    return map = new google.maps.Map($('#map-canvas')[0], mapOptions);
  };

  google.maps.event.addDomListener(window, 'load', gmapinit);

}).call(this);
