// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var connect, gmapinit, map, mapOptions;

    if (!(window.WebSocket != null)) {
      return $('#session_status').append("<p>Sorry websocket is not supported in your browser. Try something else.<\/p>");
    } else {
      mapOptions = {
        zoom: 4,
        center: new google.maps.LatLng(-34.397, 150.644),
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map($('#map-canvas')[0], mapOptions);
      connect = function() {
        var error, host, socket;

        host = "ws://localhost:9999/websocket";
        try {
          socket = new WebSocket(host);
          socket.onopen = function() {
            return $('#session_status').append("<p>Websocket is now open through: " + host + "<\/p>");
          };
          socket.onmessage = function(msg) {
            var addM, j, markoptions;

            j = JSON.parse(msg.data);
            markoptions = {
              position: new google.maps.LatLng(j.lat, j.lng),
              map: map,
              title: 'newone'
            };
            addM = new google.maps.Marker(markoptions);
            return map.panTo(addM.getPosition());
          };
          socket.onclose = function() {
            return $('#session_status').append("<p>Websocket is now closed. Thank you come again.<\/p>");
          };
          return $('#disconnect').click(function() {
            return socket.close();
          });
        } catch (_error) {
          error = _error;
          return console.log("Websocket error: " + error);
        }
      };
      gmapinit = function() {
        mapOptions = {
          zoom: 4,
          center: new google.maps.LatLng(-34.397, 150.644),
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        return map = new google.maps.Map($('#map-canvas')[0], mapOptions);
      };
      connect();
      return google.maps.event.addDomListener(window, 'load', gmapinit);
    }
  });

}).call(this);
